version: '3.4'
services:
  elastic:
    image: elasticsearch:7.2.0
    container_name: elastic
    env_file:
      - ../.global
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    environment:
      SERVER_NAME : elastic
      SERVER_HOST : elastic
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
      - config:/usr/share/elasticsearch/config
    ports:
      - 9200:9200
      - 9300:9300
    restart : unless-stopped
    networks:
      - logger


  kibana:
    image: kibana:7.2.0
    container_name: kibana
    env_file:
      - ../.global
    environment:
      SERVER_NAME: kibana
      SERVER_HOST: kibana
      ELASTICSEARCH_URL: http://elastic:9200
    volumes:
      - kconfig:/usr/share/kibana/config
      - kdata:/usr/share/kibana/data
      - knode:/usr/share/kibana/node
    ports:
      - 5601:5601
    restart: unless-stopped
    networks:
      - logger
    depends_on:
      - elastic

  logstash:
    image: logstash:7.2.0
    container_name: logstash
    env_file:
      - ../.global
    environment:
      SERVER_NAME : logstash
      SERVER_HOST : logstash
      ELASTIC_HOST: elastic:9200
    volumes:
      - logstash_config:/usr/share/logstash/config
      - logstash_data:/usr/share/logstash/data
    ports:
      - 5044:5044
    restart: unless-stopped
    networks:
      - logger
    depends_on:
      - elastic


volumes:
  data:
  logs:
  config:
  kdata:
  knode:
  kconfig:
  logstash_config:
  logstash_data:

networks:
  logger:
    name: logger